#!/bin/bash
while read oldrev newrev ref
    do
        if [[ $ref =~ .*/master$ ]];
        then
            curl -X GET "http://LOGIN:PASSWORD@JENKINS_URL/job/JOB_NAME/build?token=TOKEN"
        fi
    done